### ISSUE TITLE
JuliaInterop logo

### ISSUE THREAD

**Issue by ararslan** [JuliaInterop/Roadmap.jl#1]
Call for logo ideas!

Here's my idea:

![oie_i8khtwecwugk](https://cloud.githubusercontent.com/assets/6396159/16543234/be290840-407f-11e6-999d-7a06460fdd96.png)

**Comment by tkelman** [comment]
There's something I don't totally like about the plug analogy, not sure.

**Comment by ararslan** [comment]
Yeah. I'm not crazy about this either; it was just what I came up with from Google searching "interoperability" with a license filter.

**Comment by slundberg** [comment]
[JuliaInterop.pdf](https://github.com/JuliaInterop/Roadmap.jl/files/448392/JuliaInterop.pdf)
![juliainterop](https://cloud.githubusercontent.com/assets/3740613/18148745/6e632b84-6f90-11e6-914a-5c6c3860afa8.png)

**Comment by ararslan** [comment]
Not bad but IMHO a little too similar to the JuliaGraphs logo.

**Comment by slundberg** [comment]
that's fair.

**Comment by slundberg** [comment]
![juliainterop2](https://cloud.githubusercontent.com/assets/3740613/18149103/1929eb3c-6f93-11e6-80bc-dec7d09fa92b.png)

**Comment by ararslan** [comment]
I had envisioned something with arrows or gears but I think it would take more time than I can dedicate to it to actually make something like that. I can dig this proposal. @tkelman?

**Comment by slundberg** [comment]
Gears seem nice. One last idea.

![juliainterop3](https://cloud.githubusercontent.com/assets/3740613/18150142/7ca0afe2-6f99-11e6-872d-b794c45e9631.png)

**Comment by tkelman** [comment]
I like that one, though the mechanical engineer in me has to nitpick that gear teeth don't have straight sides, they're an involute curve

**Comment by slundberg** [comment]
Yeah, such are the limitations of royalty free vector art...

**Comment by ararslan** [comment]
I like that one as well. Unless Tony is really set on curvy teeth, I think we have a winner?

**Comment by tkelman** [comment]
I found some octave code I wrote about 9 years ago to plot involute gear teeth curves, but I don't remember what all the inputs were https://gist.github.com/0bf87a2941c11b35c48475234bcf098d

**Comment by slundberg** [comment]
Haha nice. Well I am attaching the vector version here. If you want to play with the teeth etc. go for it.

[JuliaInterop.pdf](https://github.com/JuliaInterop/Roadmap.jl/files/448507/JuliaInterop.pdf)

**Comment by ararslan** [comment]
The gears have been instated as the new logo. Thanks so much, @slundberg!
